// Code generated by pigeon; DO NOT EDIT.

package location

// NB: including all the imports make the parser generator run a bit more quickly.
import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Location",
			pos:  position{line: 24, col: 1, offset: 297},
			expr: &actionExpr{
				pos: position{line: 24, col: 13, offset: 309},
				run: (*parser).callonLocation1,
				expr: &seqExpr{
					pos: position{line: 24, col: 13, offset: 309},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 24, col: 13, offset: 309},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 16, offset: 312},
								name: "UnitId",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 23, offset: 319},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 27, offset: 323},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 30, offset: 326},
							label: "note",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 35, offset: 331},
								name: "Note",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 40, offset: 336},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 44, offset: 340},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 47, offset: 343},
							label: "ch",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 50, offset: 346},
								name: "CurrentHex",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 61, offset: 357},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 65, offset: 361},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 24, col: 68, offset: 364},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 72, offset: 368},
							label: "ph",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 75, offset: 371},
								name: "PreviousHex",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 87, offset: 383},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 91, offset: 387},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "UnitId",
			pos:  position{line: 41, col: 1, offset: 783},
			expr: &choiceExpr{
				pos: position{line: 41, col: 11, offset: 793},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 41, col: 11, offset: 793},
						run: (*parser).callonUnitId2,
						expr: &seqExpr{
							pos: position{line: 41, col: 11, offset: 793},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 41, col: 11, offset: 793},
									val:        "Courier",
									ignoreCase: false,
									want:       "\"Courier\"",
								},
								&ruleRefExpr{
									pos:  position{line: 41, col: 21, offset: 803},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 41, col: 24, offset: 806},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 41, col: 27, offset: 809},
										name: "CourierId",
									},
								},
								&andExpr{
									pos: position{line: 41, col: 37, offset: 819},
									expr: &litMatcher{
										pos:        position{line: 41, col: 38, offset: 820},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 43, col: 5, offset: 849},
						run: (*parser).callonUnitId10,
						expr: &seqExpr{
							pos: position{line: 43, col: 5, offset: 849},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 43, col: 5, offset: 849},
									val:        "Element",
									ignoreCase: false,
									want:       "\"Element\"",
								},
								&ruleRefExpr{
									pos:  position{line: 43, col: 15, offset: 859},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 43, col: 18, offset: 862},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 43, col: 21, offset: 865},
										name: "ElementId",
									},
								},
								&andExpr{
									pos: position{line: 43, col: 31, offset: 875},
									expr: &litMatcher{
										pos:        position{line: 43, col: 32, offset: 876},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 45, col: 5, offset: 905},
						run: (*parser).callonUnitId18,
						expr: &seqExpr{
							pos: position{line: 45, col: 5, offset: 905},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 45, col: 5, offset: 905},
									val:        "Fleet",
									ignoreCase: false,
									want:       "\"Fleet\"",
								},
								&ruleRefExpr{
									pos:  position{line: 45, col: 13, offset: 913},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 45, col: 16, offset: 916},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 45, col: 19, offset: 919},
										name: "FleetId",
									},
								},
								&andExpr{
									pos: position{line: 45, col: 27, offset: 927},
									expr: &litMatcher{
										pos:        position{line: 45, col: 28, offset: 928},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 47, col: 5, offset: 957},
						run: (*parser).callonUnitId26,
						expr: &seqExpr{
							pos: position{line: 47, col: 5, offset: 957},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 47, col: 5, offset: 957},
									val:        "Garrison",
									ignoreCase: false,
									want:       "\"Garrison\"",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 16, offset: 968},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 47, col: 19, offset: 971},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 22, offset: 974},
										name: "GarrisonId",
									},
								},
								&andExpr{
									pos: position{line: 47, col: 33, offset: 985},
									expr: &litMatcher{
										pos:        position{line: 47, col: 34, offset: 986},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 49, col: 5, offset: 1016},
						run: (*parser).callonUnitId34,
						expr: &seqExpr{
							pos: position{line: 49, col: 5, offset: 1016},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 49, col: 5, offset: 1016},
									val:        "Tribe",
									ignoreCase: false,
									want:       "\"Tribe\"",
								},
								&ruleRefExpr{
									pos:  position{line: 49, col: 13, offset: 1024},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 49, col: 16, offset: 1027},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 49, col: 19, offset: 1030},
										name: "TribeId",
									},
								},
								&andExpr{
									pos: position{line: 49, col: 27, offset: 1038},
									expr: &litMatcher{
										pos:        position{line: 49, col: 28, offset: 1039},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CourierId",
			pos:  position{line: 53, col: 1, offset: 1068},
			expr: &actionExpr{
				pos: position{line: 53, col: 16, offset: 1083},
				run: (*parser).callonCourierId1,
				expr: &seqExpr{
					pos: position{line: 53, col: 16, offset: 1083},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 53, col: 16, offset: 1083},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 22, offset: 1089},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 28, offset: 1095},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 34, offset: 1101},
							name: "DIGIT",
						},
						&litMatcher{
							pos:        position{line: 53, col: 40, offset: 1107},
							val:        "c",
							ignoreCase: false,
							want:       "\"c\"",
						},
						&charClassMatcher{
							pos:        position{line: 53, col: 44, offset: 1111},
							val:        "[1-9]",
							ranges:     []rune{'1', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "ElementId",
			pos:  position{line: 54, col: 1, offset: 1148},
			expr: &actionExpr{
				pos: position{line: 54, col: 16, offset: 1163},
				run: (*parser).callonElementId1,
				expr: &seqExpr{
					pos: position{line: 54, col: 16, offset: 1163},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 54, col: 16, offset: 1163},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 22, offset: 1169},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 28, offset: 1175},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 34, offset: 1181},
							name: "DIGIT",
						},
						&litMatcher{
							pos:        position{line: 54, col: 40, offset: 1187},
							val:        "e",
							ignoreCase: false,
							want:       "\"e\"",
						},
						&charClassMatcher{
							pos:        position{line: 54, col: 44, offset: 1191},
							val:        "[1-9]",
							ranges:     []rune{'1', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "FleetId",
			pos:  position{line: 55, col: 1, offset: 1228},
			expr: &actionExpr{
				pos: position{line: 55, col: 16, offset: 1243},
				run: (*parser).callonFleetId1,
				expr: &seqExpr{
					pos: position{line: 55, col: 16, offset: 1243},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 55, col: 16, offset: 1243},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 22, offset: 1249},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 28, offset: 1255},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 34, offset: 1261},
							name: "DIGIT",
						},
						&litMatcher{
							pos:        position{line: 55, col: 40, offset: 1267},
							val:        "f",
							ignoreCase: false,
							want:       "\"f\"",
						},
						&charClassMatcher{
							pos:        position{line: 55, col: 44, offset: 1271},
							val:        "[1-9]",
							ranges:     []rune{'1', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "GarrisonId",
			pos:  position{line: 56, col: 1, offset: 1308},
			expr: &actionExpr{
				pos: position{line: 56, col: 16, offset: 1323},
				run: (*parser).callonGarrisonId1,
				expr: &seqExpr{
					pos: position{line: 56, col: 16, offset: 1323},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 56, col: 16, offset: 1323},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 22, offset: 1329},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 28, offset: 1335},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 34, offset: 1341},
							name: "DIGIT",
						},
						&litMatcher{
							pos:        position{line: 56, col: 40, offset: 1347},
							val:        "g",
							ignoreCase: false,
							want:       "\"g\"",
						},
						&charClassMatcher{
							pos:        position{line: 56, col: 44, offset: 1351},
							val:        "[1-9]",
							ranges:     []rune{'1', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "TribeId",
			pos:  position{line: 57, col: 1, offset: 1388},
			expr: &actionExpr{
				pos: position{line: 57, col: 16, offset: 1403},
				run: (*parser).callonTribeId1,
				expr: &seqExpr{
					pos: position{line: 57, col: 16, offset: 1403},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 57, col: 16, offset: 1403},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 22, offset: 1409},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 28, offset: 1415},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 34, offset: 1421},
							name: "DIGIT",
						},
					},
				},
			},
		},
		{
			name: "Note",
			pos:  position{line: 59, col: 1, offset: 1469},
			expr: &actionExpr{
				pos: position{line: 59, col: 9, offset: 1477},
				run: (*parser).callonNote1,
				expr: &seqExpr{
					pos: position{line: 59, col: 9, offset: 1477},
					exprs: []any{
						&zeroOrMoreExpr{
							pos: position{line: 59, col: 9, offset: 1477},
							expr: &seqExpr{
								pos: position{line: 59, col: 10, offset: 1478},
								exprs: []any{
									&notExpr{
										pos: position{line: 59, col: 10, offset: 1478},
										expr: &charClassMatcher{
											pos:        position{line: 59, col: 11, offset: 1479},
											val:        "[\\n\\r,]",
											chars:      []rune{'\n', '\r', ','},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 59, col: 19, offset: 1487,
									},
								},
							},
						},
						&andExpr{
							pos: position{line: 59, col: 23, offset: 1491},
							expr: &litMatcher{
								pos:        position{line: 59, col: 24, offset: 1492},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "CurrentHex",
			pos:  position{line: 63, col: 1, offset: 1551},
			expr: &actionExpr{
				pos: position{line: 63, col: 15, offset: 1565},
				run: (*parser).callonCurrentHex1,
				expr: &seqExpr{
					pos: position{line: 63, col: 15, offset: 1565},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 63, col: 15, offset: 1565},
							val:        "Current",
							ignoreCase: false,
							want:       "\"Current\"",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 25, offset: 1575},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 63, col: 28, offset: 1578},
							val:        "Hex",
							ignoreCase: false,
							want:       "\"Hex\"",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 34, offset: 1584},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 63, col: 37, offset: 1587},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 41, offset: 1591},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 44, offset: 1594},
							label: "coords",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 51, offset: 1601},
								name: "Coords",
							},
						},
						&andExpr{
							pos: position{line: 63, col: 58, offset: 1608},
							expr: &litMatcher{
								pos:        position{line: 63, col: 59, offset: 1609},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "PreviousHex",
			pos:  position{line: 67, col: 1, offset: 1650},
			expr: &actionExpr{
				pos: position{line: 67, col: 16, offset: 1665},
				run: (*parser).callonPreviousHex1,
				expr: &seqExpr{
					pos: position{line: 67, col: 16, offset: 1665},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 67, col: 16, offset: 1665},
							val:        "Previous",
							ignoreCase: false,
							want:       "\"Previous\"",
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 27, offset: 1676},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 67, col: 30, offset: 1679},
							val:        "Hex",
							ignoreCase: false,
							want:       "\"Hex\"",
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 36, offset: 1685},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 67, col: 39, offset: 1688},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 43, offset: 1692},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 67, col: 46, offset: 1695},
							label: "coords",
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 53, offset: 1702},
								name: "Coords",
							},
						},
						&andExpr{
							pos: position{line: 67, col: 60, offset: 1709},
							expr: &litMatcher{
								pos:        position{line: 67, col: 61, offset: 1710},
								val:        ")",
								ignoreCase: false,
								want:       "\")\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Coords",
			pos:  position{line: 71, col: 1, offset: 1751},
			expr: &choiceExpr{
				pos: position{line: 71, col: 11, offset: 1761},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 71, col: 11, offset: 1761},
						run: (*parser).callonCoords2,
						expr: &litMatcher{
							pos:        position{line: 71, col: 11, offset: 1761},
							val:        "N/A",
							ignoreCase: false,
							want:       "\"N/A\"",
						},
					},
					&actionExpr{
						pos: position{line: 73, col: 5, offset: 1795},
						run: (*parser).callonCoords4,
						expr: &seqExpr{
							pos: position{line: 73, col: 5, offset: 1795},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 73, col: 5, offset: 1795},
									val:        "##",
									ignoreCase: false,
									want:       "\"##\"",
								},
								&ruleRefExpr{
									pos:  position{line: 73, col: 10, offset: 1800},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 73, col: 13, offset: 1803},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 73, col: 19, offset: 1809},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 73, col: 25, offset: 1815},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 73, col: 31, offset: 1821},
									name: "DIGIT",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 75, col: 5, offset: 1864},
						run: (*parser).callonCoords12,
						expr: &seqExpr{
							pos: position{line: 75, col: 5, offset: 1864},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 75, col: 5, offset: 1864},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 12, offset: 1871},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 19, offset: 1878},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 22, offset: 1881},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 28, offset: 1887},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 34, offset: 1893},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 40, offset: 1899},
									name: "DIGIT",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 80, col: 1, offset: 1942},
			expr: &notExpr{
				pos: position{line: 80, col: 10, offset: 1951},
				expr: &anyMatcher{
					line: 80, col: 11, offset: 1952,
				},
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 81, col: 1, offset: 1954},
			expr: &charClassMatcher{
				pos:        position{line: 81, col: 10, offset: 1963},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LETTER",
			pos:  position{line: 82, col: 1, offset: 1969},
			expr: &charClassMatcher{
				pos:        position{line: 82, col: 10, offset: 1978},
				val:        "[A-Z]",
				ranges:     []rune{'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SP",
			pos:  position{line: 83, col: 1, offset: 1984},
			expr: &charClassMatcher{
				pos:        position{line: 83, col: 10, offset: 1993},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "_",
			pos:  position{line: 84, col: 1, offset: 1999},
			expr: &zeroOrMoreExpr{
				pos: position{line: 84, col: 10, offset: 2008},
				expr: &charClassMatcher{
					pos:        position{line: 84, col: 10, offset: 2008},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onLocation1(id, note, ch, ph any) (any, error) {
	previousCoords := ph.(string)
	if previousCoords == "N/A" {
		previousCoords = ""
	}
	currentCoords := ch.(string)
	if currentCoords == "N/A" {
		currentCoords = ""
	}
	return Location{
		UnitId:         id.(string),
		Note:           note.(string),
		PreviousCoords: previousCoords,
		CurrentCoords:  currentCoords,
	}, nil
}

func (p *parser) callonLocation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLocation1(stack["id"], stack["note"], stack["ch"], stack["ph"])
}

func (c *current) onUnitId2(id any) (any, error) {
	return id, nil
}

func (p *parser) callonUnitId2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnitId2(stack["id"])
}

func (c *current) onUnitId10(id any) (any, error) {
	return id, nil
}

func (p *parser) callonUnitId10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnitId10(stack["id"])
}

func (c *current) onUnitId18(id any) (any, error) {
	return id, nil
}

func (p *parser) callonUnitId18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnitId18(stack["id"])
}

func (c *current) onUnitId26(id any) (any, error) {
	return id, nil
}

func (p *parser) callonUnitId26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnitId26(stack["id"])
}

func (c *current) onUnitId34(id any) (any, error) {
	return id, nil
}

func (p *parser) callonUnitId34() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnitId34(stack["id"])
}

func (c *current) onCourierId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCourierId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCourierId1()
}

func (c *current) onElementId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonElementId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onElementId1()
}

func (c *current) onFleetId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFleetId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFleetId1()
}

func (c *current) onGarrisonId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonGarrisonId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGarrisonId1()
}

func (c *current) onTribeId1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTribeId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTribeId1()
}

func (c *current) onNote1() (any, error) {
	return strings.TrimSpace(string(c.text)), nil
}

func (p *parser) callonNote1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNote1()
}

func (c *current) onCurrentHex1(coords any) (any, error) {
	return coords.(string), nil
}

func (p *parser) callonCurrentHex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCurrentHex1(stack["coords"])
}

func (c *current) onPreviousHex1(coords any) (any, error) {
	return coords.(string), nil
}

func (p *parser) callonPreviousHex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreviousHex1(stack["coords"])
}

func (c *current) onCoords2() (any, error) {
	return "N/A", nil
}

func (p *parser) callonCoords2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords2()
}

func (c *current) onCoords4() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCoords4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords4()
}

func (c *current) onCoords12() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCoords12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords12()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
