// Code generated by "stringer --type Kind"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[Backslash-1]
	_ = x[Colon-2]
	_ = x[Comma-3]
	_ = x[Dash-4]
	_ = x[DayMonthYear-5]
	_ = x[Delimiter-6]
	_ = x[Direction-7]
	_ = x[Equals-8]
	_ = x[EOL-9]
	_ = x[EOF-10]
	_ = x[Grid-11]
	_ = x[Hash-12]
	_ = x[NA-13]
	_ = x[Note-14]
	_ = x[Number-15]
	_ = x[LeftParen-16]
	_ = x[RightParen-17]
	_ = x[ScoutId-18]
	_ = x[Slash-19]
	_ = x[Spaces-20]
	_ = x[TerrainCode-21]
	_ = x[TurnYearMonth-22]
	_ = x[UnitId-23]
	_ = x[Tribe-24]
	_ = x[Courier-25]
	_ = x[Element-26]
	_ = x[Fleet-27]
	_ = x[Garrison-28]
	_ = x[Current-29]
	_ = x[Hex-30]
	_ = x[Previous-31]
	_ = x[Turn-32]
	_ = x[Season-33]
	_ = x[Next-34]
	_ = x[Weather-35]
	_ = x[Goes-36]
	_ = x[To-37]
	_ = x[Movement-38]
	_ = x[Move-39]
	_ = x[Scout-40]
	_ = x[Status-41]
}

const _Kind_name = "TextBackslashColonCommaDashDayMonthYearDelimiterDirectionEqualsEOLEOFGridHashNANoteNumberLeftParenRightParenScoutIdSlashSpacesTerrainCodeTurnYearMonthUnitIdTribeCourierElementFleetGarrisonCurrentHexPreviousTurnSeasonNextWeatherGoesToMovementMoveScoutStatus"

var _Kind_index = [...]uint16{0, 4, 13, 18, 23, 27, 39, 48, 57, 63, 66, 69, 73, 77, 79, 83, 89, 98, 108, 115, 120, 126, 137, 150, 156, 161, 168, 175, 180, 188, 195, 198, 206, 210, 216, 220, 227, 231, 233, 241, 245, 250, 256}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
