// Generated by godel - DO NOT EDIT
// Source: handlers.go

import Model, { attr } from '@ember-data/model';

export default class TimezoneModel extends Model {
  @attr('string') canonicalName;
  @attr('date') createdAt;
  @attr('date') updatedAt;
}
