// Generated by godel - DO NOT EDIT
// Source: handlers.go

import Model, { attr } from '@ember-data/model';

export default class UserModel extends Model {
  @attr('string') username;
  @attr('string') email;
  @attr('string') timezone;
  @attr() roles;
  @attr() permissions;
  @attr('date') createdAt;
  @attr('date') updatedAt;
}
