// Generated by godel - DO NOT EDIT
// Source: service.go

import Model, { attr } from '@ember-data/model';

export default class VersionModel extends Model {
  @attr('string') short;
  @attr('string') full;
}
