// Copyright (c) 2025 Michael D Henderson. All rights reserved.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseStruct(t *testing.T) {
	// Create a temporary test file
	testFile := filepath.Join(t.TempDir(), "test.go")
	testCode := `package test

import "time"

type TestView struct {
	ID          string          ` + "`jsonapi:\"primary,tests\"`" + `
	Name        string          ` + "`jsonapi:\"attr,name\"`" + `
	Email       string          ` + "`jsonapi:\"attr,email\"`" + `
	Age         int             ` + "`jsonapi:\"attr,age\"`" + `
	IsActive    bool            ` + "`jsonapi:\"attr,isActive\"`" + `
	CreatedAt   time.Time       ` + "`jsonapi:\"attr,createdAt,iso8601\"`" + `
	Tags        []string        ` + "`jsonapi:\"attr,tags,omitempty\"`" + `
	Settings    map[string]bool ` + "`jsonapi:\"attr,settings,omitempty\"`" + `
}
`

	if err := os.WriteFile(testFile, []byte(testCode), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	model, err := parseStruct(testFile, "TestView")
	if err != nil {
		t.Fatalf("parseStruct failed: %v", err)
	}

	// Verify model name (uses exact name from jsonapi tag, not singularized)
	if model.Name != "tests" {
		t.Errorf("expected model name 'tests', got '%s'", model.Name)
	}

	// Verify field count
	expectedFields := 7
	if len(model.Fields) != expectedFields {
		t.Errorf("expected %d fields, got %d", expectedFields, len(model.Fields))
	}

	// Verify specific fields
	tests := []struct {
		name      string
		emberType string
		isArray   bool
		isObject  bool
	}{
		{"name", "string", false, false},
		{"email", "string", false, false},
		{"age", "number", false, false},
		{"isActive", "boolean", false, false},
		{"createdAt", "date", false, false},
		{"tags", "", true, false},
		{"settings", "", false, true},
	}

	for _, tt := range tests {
		found := false
		for _, field := range model.Fields {
			if field.Name == tt.name {
				found = true
				if field.EmberType != tt.emberType {
					t.Errorf("field %s: expected type '%s', got '%s'", tt.name, tt.emberType, field.EmberType)
				}
				if field.IsArray != tt.isArray {
					t.Errorf("field %s: expected isArray %v, got %v", tt.name, tt.isArray, field.IsArray)
				}
				if field.IsObject != tt.isObject {
					t.Errorf("field %s: expected isObject %v, got %v", tt.name, tt.isObject, field.IsObject)
				}
				break
			}
		}
		if !found {
			t.Errorf("field %s not found in parsed model", tt.name)
		}
	}
}

func TestParseStruct_NotFound(t *testing.T) {
	testFile := filepath.Join(t.TempDir(), "test.go")
	testCode := `package test

type OtherStruct struct {
	Name string
}
`

	if err := os.WriteFile(testFile, []byte(testCode), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	_, err := parseStruct(testFile, "NonExistent")
	if err == nil {
		t.Error("expected error for non-existent struct, got nil")
	}
}

func TestMapGoTypeToEmber(t *testing.T) {
	tests := []struct {
		goType    string
		emberType string
		isArray   bool
		isObject  bool
	}{
		{"string", "string", false, false},
		{"time.Time", "date", false, false},
		{"bool", "boolean", false, false},
		{"int", "number", false, false},
		{"int64", "number", false, false},
		{"float64", "number", false, false},
		{"[]string", "", true, false},
		{"[]int", "", true, false},
		{"map[string]bool", "", false, true},
		{"map[string]string", "", false, true},
	}

	for _, tt := range tests {
		emberType, isArray, isObject := mapGoTypeToEmber(tt.goType)
		if emberType != tt.emberType {
			t.Errorf("mapGoTypeToEmber(%s): expected type '%s', got '%s'", tt.goType, tt.emberType, emberType)
		}
		if isArray != tt.isArray {
			t.Errorf("mapGoTypeToEmber(%s): expected isArray %v, got %v", tt.goType, tt.isArray, isArray)
		}
		if isObject != tt.isObject {
			t.Errorf("mapGoTypeToEmber(%s): expected isObject %v, got %v", tt.goType, tt.isObject, isObject)
		}
	}
}

func TestGenerateEmberModel(t *testing.T) {
	model := &Model{
		Name: "users",
		Fields: []Field{
			{Name: "username", EmberType: "string"},
			{Name: "email", EmberType: "string"},
			{Name: "age", EmberType: "number"},
			{Name: "createdAt", EmberType: "date"},
			{Name: "tags", IsArray: true},
			{Name: "settings", IsObject: true},
		},
	}

	outputFile := filepath.Join(t.TempDir(), "user.js")
	if err := generateEmberModel(model, outputFile); err != nil {
		t.Fatalf("generateEmberModel failed: %v", err)
	}

	// Read generated file
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	generated := string(content)

	// Verify content
	expectedStrings := []string{
		"// Generated by godel - DO NOT EDIT",
		"import Model, { attr } from '@ember-data/model'",
		"export default class UsersModel extends Model",
		"@attr('string') username;",
		"@attr('string') email;",
		"@attr('number') age;",
		"@attr('date') createdAt;",
		"@attr() tags;",
		"@attr() settings;",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(generated, expected) {
			t.Errorf("generated file missing expected string: %s", expected)
		}
	}
}

func TestTypeToString(t *testing.T) {
	// This is tested indirectly through TestParseStruct,
	// but we could add more specific tests if needed
}

func TestEndToEnd(t *testing.T) {
	// Create a temporary test file with a realistic struct
	testFile := filepath.Join(t.TempDir(), "handlers.go")
	testCode := `package handlers

import "time"

type UserView struct {
	ID          string          ` + "`jsonapi:\"primary,users\"`" + `
	Username    string          ` + "`jsonapi:\"attr,username\"`" + `
	Email       string          ` + "`jsonapi:\"attr,email\"`" + `
	Timezone    string          ` + "`jsonapi:\"attr,timezone\"`" + `
	Roles       []string        ` + "`jsonapi:\"attr,roles,omitempty\"`" + `
	Permissions map[string]bool ` + "`jsonapi:\"attr,permissions,omitempty\"`" + `
	CreatedAt   time.Time       ` + "`jsonapi:\"attr,createdAt,iso8601\"`" + `
	UpdatedAt   time.Time       ` + "`jsonapi:\"attr,updatedAt,iso8601\"`" + `
}
`

	if err := os.WriteFile(testFile, []byte(testCode), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	// Parse the struct
	model, err := parseStruct(testFile, "UserView")
	if err != nil {
		t.Fatalf("parseStruct failed: %v", err)
	}

	// Generate the model
	outputFile := filepath.Join(t.TempDir(), "user.js")
	if err := generateEmberModel(model, outputFile); err != nil {
		t.Fatalf("generateEmberModel failed: %v", err)
	}

	// Verify the generated file
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	generated := string(content)

	// Check for all expected fields
	expectedFields := []string{
		"@attr('string') username;",
		"@attr('string') email;",
		"@attr('string') timezone;",
		"@attr() roles;",
		"@attr() permissions;",
		"@attr('date') createdAt;",
		"@attr('date') updatedAt;",
	}

	for _, expected := range expectedFields {
		if !strings.Contains(generated, expected) {
			t.Errorf("generated file missing expected field: %s", expected)
		}
	}

	// Verify model class name
	if !strings.Contains(generated, "export default class UsersModel extends Model") {
		t.Error("generated file missing correct class declaration")
	}
}
