// Code generated by "stringer --type Kind"; DO NOT EDIT.

package lexers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[Backslash-1]
	_ = x[Colon-2]
	_ = x[Comma-3]
	_ = x[Dash-4]
	_ = x[Delimiter-5]
	_ = x[Direction-6]
	_ = x[Equals-7]
	_ = x[EOL-8]
	_ = x[EOF-9]
	_ = x[Grid-10]
	_ = x[Hash-11]
	_ = x[NA-12]
	_ = x[Note-13]
	_ = x[Number-14]
	_ = x[LeftParen-15]
	_ = x[RightParen-16]
	_ = x[Slash-17]
	_ = x[Spaces-18]
	_ = x[TerrainCode-19]
	_ = x[TurnYearMonth-20]
	_ = x[UnitId-21]
	_ = x[Tribe-22]
	_ = x[Courier-23]
	_ = x[Element-24]
	_ = x[Fleet-25]
	_ = x[Garrison-26]
	_ = x[Current-27]
	_ = x[Hex-28]
	_ = x[Previous-29]
	_ = x[Turn-30]
	_ = x[Season-31]
	_ = x[Next-32]
	_ = x[Weather-33]
	_ = x[Goes-34]
	_ = x[To-35]
	_ = x[Movement-36]
	_ = x[Move-37]
	_ = x[Scout-38]
	_ = x[Status-39]
}

const _Kind_name = "TextBackslashColonCommaDashDelimiterDirectionEqualsEOLEOFGridHashNANoteNumberLeftParenRightParenSlashSpacesTerrainCodeTurnYearMonthUnitIdTribeCourierElementFleetGarrisonCurrentHexPreviousTurnSeasonNextWeatherGoesToMovementMoveScoutStatus"

var _Kind_index = [...]uint8{0, 4, 13, 18, 23, 27, 36, 45, 51, 54, 57, 61, 65, 67, 71, 77, 86, 96, 101, 107, 118, 131, 137, 142, 149, 156, 161, 169, 176, 179, 187, 191, 197, 201, 208, 212, 214, 222, 226, 231, 237}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
