// Code generated by "stringer --type Kind"; DO NOT EDIT.

package lexers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[Comma-1]
	_ = x[Dash-2]
	_ = x[Delimiter-3]
	_ = x[Equals-4]
	_ = x[EOL-5]
	_ = x[EOF-6]
	_ = x[Grid-7]
	_ = x[Hash-8]
	_ = x[Note-9]
	_ = x[Number-10]
	_ = x[LeftParen-11]
	_ = x[RightParen-12]
	_ = x[Slash-13]
	_ = x[Spaces-14]
	_ = x[Tribe-15]
	_ = x[Courier-16]
	_ = x[Element-17]
	_ = x[Fleet-18]
	_ = x[Garrison-19]
	_ = x[Current-20]
	_ = x[Hex-21]
	_ = x[Previous-22]
	_ = x[Turn-23]
	_ = x[Season-24]
	_ = x[Next-25]
	_ = x[Weather-26]
}

const _Kind_name = "TextCommaDashDelimiterEqualsEOLEOFGridHashNoteNumberLeftParenRightParenSlashSpacesTribeCourierElementFleetGarrisonCurrentHexPreviousTurnSeasonNextWeather"

var _Kind_index = [...]uint8{0, 4, 9, 13, 22, 28, 31, 34, 38, 42, 46, 52, 61, 71, 76, 82, 87, 94, 101, 106, 114, 121, 124, 132, 136, 142, 146, 153}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
