// Code generated by "stringer --type Kind"; DO NOT EDIT.

package lexers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[Backslash-1]
	_ = x[Colon-2]
	_ = x[Comma-3]
	_ = x[Dash-4]
	_ = x[Delimiter-5]
	_ = x[Equals-6]
	_ = x[EOL-7]
	_ = x[EOF-8]
	_ = x[Grid-9]
	_ = x[Hash-10]
	_ = x[NA-11]
	_ = x[Note-12]
	_ = x[Number-13]
	_ = x[LeftParen-14]
	_ = x[RightParen-15]
	_ = x[Slash-16]
	_ = x[Spaces-17]
	_ = x[TurnYearMonth-18]
	_ = x[UnitId-19]
	_ = x[Tribe-20]
	_ = x[Courier-21]
	_ = x[Element-22]
	_ = x[Fleet-23]
	_ = x[Garrison-24]
	_ = x[Current-25]
	_ = x[Hex-26]
	_ = x[Previous-27]
	_ = x[Turn-28]
	_ = x[Season-29]
	_ = x[Next-30]
	_ = x[Weather-31]
}

const _Kind_name = "TextBackslashColonCommaDashDelimiterEqualsEOLEOFGridHashNANoteNumberLeftParenRightParenSlashSpacesTurnYearMonthUnitIdTribeCourierElementFleetGarrisonCurrentHexPreviousTurnSeasonNextWeather"

var _Kind_index = [...]uint8{0, 4, 13, 18, 23, 27, 36, 42, 45, 48, 52, 56, 58, 62, 68, 77, 87, 92, 98, 111, 117, 122, 129, 136, 141, 149, 156, 159, 167, 171, 177, 181, 188}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
