// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package sqlc

import (
	"context"
)

const getSessionData = `-- name: GetSessionData :many
SELECT s.csrf,
       u.user_id,
       u.handle,
       ur.role_id
FROM sessions s,
     users u,
     user_roles ur
WHERE s.session_id = ?1
  AND s.expires_at > ?2
  AND u.user_id = s.user_id
  AND ur.user_id = u.user_id
`

type GetSessionDataParams struct {
	SessionID string
	ExpiresAt int64
}

type GetSessionDataRow struct {
	Csrf   string
	UserID int64
	Handle string
	RoleID string
}

func (q *Queries) GetSessionData(ctx context.Context, arg GetSessionDataParams) ([]GetSessionDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionData, arg.SessionID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionDataRow
	for rows.Next() {
		var i GetSessionDataRow
		if err := rows.Scan(
			&i.Csrf,
			&i.UserID,
			&i.Handle,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
