// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
)

const createUserSecrets = `-- name: CreateUserSecrets :exec

INSERT INTO user_secrets (user_id,
                          hashed_password,
                          last_login,
                          created_at,
                          updated_at)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5)
`

type CreateUserSecretsParams struct {
	UserID         int64
	HashedPassword string
	LastLogin      int64
	CreatedAt      int64
	UpdatedAt      int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateUserSecrets creates a secrets record for the user.
// The password is stored as a bcrypt hash.
func (q *Queries) CreateUserSecrets(ctx context.Context, arg CreateUserSecretsParams) error {
	_, err := q.db.ExecContext(ctx, createUserSecrets,
		arg.UserID,
		arg.HashedPassword,
		arg.LastLogin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT role_id
FROM user_roles
WHERE user_id = ?1
`

// GetUserRoles returns the roles for a user.
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSecrets = `-- name: GetUserSecrets :one
SELECT hashed_password
FROM user_secrets
WHERE user_id = ?1
`

// GetUserSecrets returns the password for a user.
// The password is stored as a bcrypt hash.
func (q *Queries) GetUserSecrets(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSecrets, userID)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user_secrets
SET hashed_password = ?1,
    updated_at      = ?2
WHERE user_id = ?3
`

type UpdateUserPasswordParams struct {
	HashedPassword string
	UpdatedAt      int64
	UserID         int64
}

// UpdateUserPassword updates password for a user.
// The password is stored as a bcrypt hash.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashedPassword, arg.UpdatedAt, arg.UserID)
	return err
}
