// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserRoles = `-- name: GetUserRoles :many
SELECT role_id
FROM user_roles
WHERE user_id = ?1
`

// GetUserRoles returns the roles for a user.
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSecret = `-- name: GetUserSecret :one
SELECT hashed_password
FROM user_secrets
WHERE user_id = ?1
`

// GetUserSecret returns the password for a user.
// The password is stored as a bcrypt hash.
func (q *Queries) GetUserSecret(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSecret, userID)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE
FROM user_roles
WHERE user_id = ?1
  AND role_id = ?2
`

type RemoveUserRoleParams struct {
	UserID int64
	RoleID string
}

// RemoveUserRole removes a role from a user.
func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeUserRole, arg.UserID, arg.RoleID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE user_secrets
SET last_login = ?1
WHERE user_id = ?2
`

type UpdateUserLastLoginParams struct {
	LastLogin int64
	UserID    int64
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, arg.LastLogin, arg.UserID)
	return err
}

const upsertUserRole = `-- name: UpsertUserRole :exec
INSERT INTO user_roles (user_id, role_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (user_id, role_id) DO UPDATE SET updated_at = excluded.updated_at
`

type UpsertUserRoleParams struct {
	UserID    int64
	RoleID    string
	CreatedAt int64
	UpdatedAt int64
}

// UpsertUserRole assigns a role to a user.
func (q *Queries) UpsertUserRole(ctx context.Context, arg UpsertUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserRole,
		arg.UserID,
		arg.RoleID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserSecret = `-- name: UpsertUserSecret :exec

INSERT INTO user_secrets (user_id,
                          hashed_password,
                          plaintext_password,
                          last_login,
                          created_at,
                          updated_at)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6)
ON CONFLICT (user_id) DO UPDATE SET hashed_password    = excluded.hashed_password,
                                    plaintext_password = excluded.plaintext_password,
                                    last_login         = excluded.last_login,
                                    updated_at         = excluded.updated_at
`

type UpsertUserSecretParams struct {
	UserID            int64
	HashedPassword    string
	PlaintextPassword sql.NullString
	LastLogin         int64
	CreatedAt         int64
	UpdatedAt         int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// UpsertUserSecret creates a secrets record for the user.
// The password is stored as a bcrypt hash.
func (q *Queries) UpsertUserSecret(ctx context.Context, arg UpsertUserSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSecret,
		arg.UserID,
		arg.HashedPassword,
		arg.PlaintextPassword,
		arg.LastLogin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
