// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"
)

const getConfigKeyValue = `-- name: GetConfigKeyValue :one

SELECT value
FROM config
WHERE key = ?1
`

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// GetConfigKeyValue does
func (q *Queries) GetConfigKeyValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigKeyValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
