// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (document_id, document_created_by, document_created_at, document_path)
VALUES (?1, ?2, ?3, ?4)
RETURNING document_id
`

type CreateDocumentParams struct {
	DocumentID        string
	DocumentCreatedBy int64
	DocumentCreatedAt int64
	DocumentPath      string
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateDocument does
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.DocumentID,
		arg.DocumentCreatedBy,
		arg.DocumentCreatedAt,
		arg.DocumentPath,
	)
	var document_id string
	err := row.Scan(&document_id)
	return document_id, err
}
