// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, description, active_turn_id, setup_turn_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING game_id
`

type CreateGameParams struct {
	Code         string
	Description  string
	ActiveTurnID int64
	SetupTurnID  int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Code,
		arg.Description,
		arg.ActiveTurnID,
		arg.SetupTurnID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var game_id int64
	err := row.Scan(&game_id)
	return game_id, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE
FROM games
WHERE game_id = ?1
`

func (q *Queries) DeleteGame(ctx context.Context, gameID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGame, gameID)
	return err
}

const readGame = `-- name: ReadGame :one
SELECT games.game_id,
       games.code,
       games.is_active,
       games.description,
       active_turn.turn_id    AS active_turn_id,
       active_turn.turn_year  AS active_turn_year,
       active_turn.turn_month AS active_turn_month,
       active_turn.turn_no    AS active_turn_no,
       active_turn.orders_due AS orders_due
FROM games,
     game_turns AS active_turn
WHERE games.game_id = ?1
  AND active_turn.turn_id = games.active_turn
`

type ReadGameRow struct {
	GameID          int64
	Code            string
	IsActive        bool
	Description     string
	ActiveTurnID    int64
	ActiveTurnYear  int64
	ActiveTurnMonth int64
	ActiveTurnNo    int64
	OrdersDue       int64
}

func (q *Queries) ReadGame(ctx context.Context, gameID int64) (ReadGameRow, error) {
	row := q.db.QueryRowContext(ctx, readGame, gameID)
	var i ReadGameRow
	err := row.Scan(
		&i.GameID,
		&i.Code,
		&i.IsActive,
		&i.Description,
		&i.ActiveTurnID,
		&i.ActiveTurnYear,
		&i.ActiveTurnMonth,
		&i.ActiveTurnNo,
		&i.OrdersDue,
	)
	return i, err
}

const readGames = `-- name: ReadGames :many
SELECT games.game_id,
       games.code,
       games.is_active,
       games.description,
       active_turn.turn_id    AS active_turn_id,
       active_turn.turn_year  AS active_turn_year,
       active_turn.turn_month AS active_turn_month,
       active_turn.turn_no    AS active_turn_no,
       active_turn.orders_due AS orders_due
FROM games,
     game_turns AS active_turn
WHERE active_turn.turn_id = games.active_turn
`

type ReadGamesRow struct {
	GameID          int64
	Code            string
	IsActive        bool
	Description     string
	ActiveTurnID    int64
	ActiveTurnYear  int64
	ActiveTurnMonth int64
	ActiveTurnNo    int64
	OrdersDue       int64
}

func (q *Queries) ReadGames(ctx context.Context) ([]ReadGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, readGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadGamesRow
	for rows.Next() {
		var i ReadGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.Code,
			&i.IsActive,
			&i.Description,
			&i.ActiveTurnID,
			&i.ActiveTurnYear,
			&i.ActiveTurnMonth,
			&i.ActiveTurnNo,
			&i.OrdersDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameActiveTurn = `-- name: UpdateGameActiveTurn :exec
UPDATE games
SET active_turn_id = ?1,
    updated_at     = ?2
WHERE game_id = ?3
`

type UpdateGameActiveTurnParams struct {
	ActiveTurnID int64
	UpdatedAt    int64
	GameID       int64
}

func (q *Queries) UpdateGameActiveTurn(ctx context.Context, arg UpdateGameActiveTurnParams) error {
	_, err := q.db.ExecContext(ctx, updateGameActiveTurn, arg.ActiveTurnID, arg.UpdatedAt, arg.GameID)
	return err
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (code, description, active_turn_id, setup_turn_id, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (code) DO UPDATE
    SET description    = excluded.description,
        is_active      = excluded.is_active,
        active_turn_id = excluded.active_turn_id,
        setup_turn_id  = excluded.setup_turn_id,
        updated_at     = excluded.updated_at
RETURNING game_id
`

type UpsertGameParams struct {
	Code         string
	Description  string
	ActiveTurnID int64
	SetupTurnID  int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertGame,
		arg.Code,
		arg.Description,
		arg.ActiveTurnID,
		arg.SetupTurnID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var game_id int64
	err := row.Scan(&game_id)
	return game_id, err
}
