// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, description, active_turn, setup_turn, orders_due, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (code)
    DO UPDATE SET description = excluded.description,
                  active_turn = excluded.active_turn,
                  setup_turn  = excluded.setup_turn,
                  orders_due  = excluded.orders_due,
                  updated_at  = excluded.updated_at
RETURNING game_id
`

type CreateGameParams struct {
	Code        string
	Description string
	ActiveTurn  string
	SetupTurn   string
	OrdersDue   int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Code,
		arg.Description,
		arg.ActiveTurn,
		arg.SetupTurn,
		arg.OrdersDue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var game_id int64
	err := row.Scan(&game_id)
	return game_id, err
}

const createGameTurn = `-- name: CreateGameTurn :exec
INSERT INTO game_turns(game_id, turn, turn_year, turn_month, turn_no, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (game_id, turn)
    DO UPDATE SET turn_year  = excluded.turn_year,
                  turn_month = excluded.turn,
                  turn_no    = excluded.turn_no,
                  updated_at = excluded.updated_at
`

type CreateGameTurnParams struct {
	GameID    int64
	Turn      string
	TurnYear  int64
	TurnMonth int64
	TurnNo    int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateGameTurn(ctx context.Context, arg CreateGameTurnParams) error {
	_, err := q.db.ExecContext(ctx, createGameTurn,
		arg.GameID,
		arg.Turn,
		arg.TurnYear,
		arg.TurnMonth,
		arg.TurnNo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE
FROM games
WHERE game_id = ?1
`

func (q *Queries) DeleteGame(ctx context.Context, gameID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGame, gameID)
	return err
}

const readGame = `-- name: ReadGame :one
;

SELECT games.game_id,
       games.code,
       games.description,
       games.active_turn,
       game_turns.turn_year,
       game_turns.turn_month,
       games.setup_turn,
       games.orders_due
FROM games,
     game_turns
WHERE games.game_id = ?1
  AND games.game_id = game_turns.game_id
  AND game_turns.turn = games.active_turn
`

type ReadGameRow struct {
	GameID      int64
	Code        string
	Description string
	ActiveTurn  string
	TurnYear    int64
	TurnMonth   int64
	SetupTurn   string
	OrdersDue   int64
}

func (q *Queries) ReadGame(ctx context.Context, gameID int64) (ReadGameRow, error) {
	row := q.db.QueryRowContext(ctx, readGame, gameID)
	var i ReadGameRow
	err := row.Scan(
		&i.GameID,
		&i.Code,
		&i.Description,
		&i.ActiveTurn,
		&i.TurnYear,
		&i.TurnMonth,
		&i.SetupTurn,
		&i.OrdersDue,
	)
	return i, err
}

const readGames = `-- name: ReadGames :many
SELECT games.game_id,
       games.code,
       games.description,
       games.active_turn,
       game_turns.turn_year,
       game_turns.turn_month,
       games.setup_turn,
       games.orders_due
FROM games,
     game_turns
WHERE games.game_id = game_turns.game_id
  AND game_turns.turn = games.active_turn
`

type ReadGamesRow struct {
	GameID      int64
	Code        string
	Description string
	ActiveTurn  string
	TurnYear    int64
	TurnMonth   int64
	SetupTurn   string
	OrdersDue   int64
}

func (q *Queries) ReadGames(ctx context.Context) ([]ReadGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, readGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadGamesRow
	for rows.Next() {
		var i ReadGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.Code,
			&i.Description,
			&i.ActiveTurn,
			&i.TurnYear,
			&i.TurnMonth,
			&i.SetupTurn,
			&i.OrdersDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET active_turn = ?1,
    setup_turn  = ?2,
    orders_due  = ?3,
    updated_at  = ?4
WHERE game_id = ?5
`

type UpdateGameParams struct {
	ActiveTurn string
	SetupTurn  string
	OrdersDue  int64
	UpdatedAt  int64
	GameID     int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame,
		arg.ActiveTurn,
		arg.SetupTurn,
		arg.OrdersDue,
		arg.UpdatedAt,
		arg.GameID,
	)
	return err
}

const updateGameActiveTurn = `-- name: UpdateGameActiveTurn :exec
UPDATE games
SET active_turn = ?1,
    updated_at  = ?2
WHERE game_id = ?3
`

type UpdateGameActiveTurnParams struct {
	Turn      string
	UpdatedAt int64
	GameID    int64
}

func (q *Queries) UpdateGameActiveTurn(ctx context.Context, arg UpdateGameActiveTurnParams) error {
	_, err := q.db.ExecContext(ctx, updateGameActiveTurn, arg.Turn, arg.UpdatedAt, arg.GameID)
	return err
}
