// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migrations.sql

package sqlc

import (
	"context"
)

const getDatabaseMigrationsApplied = `-- name: GetDatabaseMigrationsApplied :many
SELECT id, migration_id, file_name, applied_at
FROM schema_migrations
`

type GetDatabaseMigrationsAppliedRow struct {
	ID          int64
	MigrationID string
	FileName    string
	AppliedAt   int64
}

func (q *Queries) GetDatabaseMigrationsApplied(ctx context.Context) ([]GetDatabaseMigrationsAppliedRow, error) {
	rows, err := q.db.QueryContext(ctx, getDatabaseMigrationsApplied)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDatabaseMigrationsAppliedRow
	for rows.Next() {
		var i GetDatabaseMigrationsAppliedRow
		if err := rows.Scan(
			&i.ID,
			&i.MigrationID,
			&i.FileName,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseVersion = `-- name: GetDatabaseVersion :one

SELECT value
FROM config
WHERE key = 'schema.version'
`

// Copyright (c) 2025 Michael D Henderson. All rights reserved.
func (q *Queries) GetDatabaseVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseVersion)
	var value string
	err := row.Scan(&value)
	return value, err
}
