// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Clan struct {
	ClanID    int64
	UserID    int64
	GameID    string
	Clan      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Game struct {
	GameID      int64
	Description string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Role struct {
	RoleID      string
	IsActive    bool
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SchemaMigration struct {
	ID        int64
	Name      string
	AppliedAt time.Time
}

type SchemaVersion struct {
	ID        int64
	Version   int64
	AppliedAt time.Time
}

type Session struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	UserID    int64
	Handle    string
	Email     string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSecret struct {
	UserID         int64
	HashedPassword string
	LastLogin      int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
