// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Clan struct {
	ClanID      int64
	GameID      string
	UserID      int64
	Clan        int64
	SetupTurnNo int64
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Config struct {
	Key       string
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Document struct {
	DocumentID        string
	DocumentCreatedBy int64
	DocumentCreatedAt int64
	DocumentPath      string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Element struct {
	ElementType   string
	ElementSuffix string
	Description   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Game struct {
	GameID         int64
	Description    string
	SetupTurnNo    int64
	SetupTurnYear  int64
	SetupTurnMonth int64
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Role struct {
	RoleID      string
	IsActive    bool
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SchemaMigration struct {
	ID        int64
	Name      string
	AppliedAt time.Time
}

type SchemaVersion struct {
	ID        int64
	Version   int64
	AppliedAt time.Time
}

type Session struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TurnReport struct {
	TurnReportID int64
	DocumentID   int64
	GameID       int64
	UserID       int64
	TurnNo       int64
}

type TurnReportAcl struct {
	TurnReportID int64
	UserID       int64
	IsOwner      bool
	CanRead      bool
	CanWrite     bool
	CanDelete    bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	UserID    int64
	Handle    string
	Email     string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSecret struct {
	UserID         int64
	HashedPassword string
	LastLogin      int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
