// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Clan struct {
	ClanID      int64
	GameID      string
	UserID      int64
	Clan        int64
	SetupTurnNo int64
	IsActive    bool
	CreatedAt   int64
	UpdatedAt   int64
}

type Config struct {
	Key       string
	Value     string
	CreatedAt int64
	UpdatedAt int64
}

type Document struct {
	DocumentID    int64
	MimeType      string
	ContentsHash  string
	ContentLength int64
	CreatedAt     int64
	UpdatedAt     int64
}

type DocumentAcl struct {
	DocumentID   int64
	UserID       int64
	DocumentName string
	CreatedBy    int64
	IsOwner      bool
	CanRead      bool
	CanWrite     bool
	CanDelete    bool
	CreatedAt    int64
	UpdatedAt    int64
}

type DocumentContent struct {
	DocumentID int64
	Contents   []byte
	CreatedAt  int64
	UpdatedAt  int64
}

type Element struct {
	ElementType   string
	ElementSuffix string
	Description   string
	CreatedAt     int64
	UpdatedAt     int64
}

type Game struct {
	GameID         int64
	Description    string
	SetupTurnNo    int64
	SetupTurnYear  int64
	SetupTurnMonth int64
	IsActive       bool
	CreatedAt      int64
	UpdatedAt      int64
}

type Role struct {
	RoleID      string
	IsActive    bool
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

type SchemaMigration struct {
	ID          int64
	MigrationID string
	FileName    string
	AppliedAt   int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt int64
	CreatedAt int64
	UpdatedAt int64
}

type TurnReport struct {
	TurnReportID int64
	GameID       int64
	UserID       int64
	DocumentID   int64
	TurnNo       int64
	ClanID       int64
	CreatedAt    int64
	UpdatedAt    int64
}

type User struct {
	UserID    int64
	Username  string
	Email     string
	Timezone  string
	CreatedAt int64
	UpdatedAt int64
}

type UserRole struct {
	UserID    int64
	RoleID    string
	CreatedAt int64
	UpdatedAt int64
}

type UserSecret struct {
	UserID         int64
	HashedPassword string
	LastLogin      int64
	CreatedAt      int64
	UpdatedAt      int64
}
