// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (session_id, csrf, user_id, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateSession creates a session for the user.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.SessionID,
		arg.Csrf,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_id = ?1
`

// DeleteSession deletes a session.
func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT csrf, user_id, expires_at
FROM sessions
WHERE session_id = ?1
`

type GetSessionRow struct {
	Csrf      string
	UserID    int64
	ExpiresAt int64
}

// GetSession returns the session tied to an id.
func (q *Queries) GetSession(ctx context.Context, sessionID string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i GetSessionRow
	err := row.Scan(&i.Csrf, &i.UserID, &i.ExpiresAt)
	return i, err
}

const reapSessions = `-- name: ReapSessions :exec
DELETE FROM sessions
WHERE expires_at <= ?1
`

// ReapSessions deletes expired sessions.
func (q *Queries) ReapSessions(ctx context.Context, nowUtc int64) error {
	_, err := q.db.ExecContext(ctx, reapSessions, nowUtc)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET expires_at = ?1
WHERE session_id = ?2
`

type UpdateSessionParams struct {
	ExpiresAt int64
	SessionID string
}

// UpdateSession updates a session.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.ExpiresAt, arg.SessionID)
	return err
}
