// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (session_id, csrf, user_id, expires_at)
VALUES(?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt time.Time
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateSession creates a session for the user.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.SessionID,
		arg.Csrf,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const getSession = `-- name: GetSession :one
SELECT csrf, user_id, expires_at
FROM sessions
WHERE session_id = ?1
`

type GetSessionRow struct {
	Csrf      string
	UserID    int64
	ExpiresAt time.Time
}

// GetSession returns the session tied to an id.
func (q *Queries) GetSession(ctx context.Context, sessionID string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i GetSessionRow
	err := row.Scan(&i.Csrf, &i.UserID, &i.ExpiresAt)
	return i, err
}
