// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (session_id, csrf, user_id, expires_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateSessionParams struct {
	SessionID string
	Csrf      string
	UserID    int64
	ExpiresAt int64
	CreatedAt int64
	UpdatedAt int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateSession creates a session for the user.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.SessionID,
		arg.Csrf,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE
FROM sessions
WHERE session_id = ?1
`

// DeleteSession deletes a session.
func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT csrf, user_id, expires_at
FROM sessions
WHERE session_id = ?1
`

type GetSessionRow struct {
	Csrf      string
	UserID    int64
	ExpiresAt int64
}

// GetSession returns the session tied to an id.
func (q *Queries) GetSession(ctx context.Context, sessionID string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i GetSessionRow
	err := row.Scan(&i.Csrf, &i.UserID, &i.ExpiresAt)
	return i, err
}

const readSessionData = `-- name: ReadSessionData :one
SELECT sessions.csrf,
       users.user_id,
       users.handle,
       users.is_active,
       users.is_admin,
       users.is_gm,
       users.is_guest,
       users.is_player,
       users.is_service,
       users.is_sysop,
       users.is_user
FROM sessions,
     users
WHERE sessions.session_id = ?1
  AND sessions.expires_at > ?2
  AND users.user_id = sessions.user_id
`

type ReadSessionDataParams struct {
	SessionID string
	ExpiresAt int64
}

type ReadSessionDataRow struct {
	Csrf      string
	UserID    int64
	Handle    string
	IsActive  bool
	IsAdmin   bool
	IsGm      bool
	IsGuest   bool
	IsPlayer  bool
	IsService bool
	IsSysop   bool
	IsUser    bool
}

func (q *Queries) ReadSessionData(ctx context.Context, arg ReadSessionDataParams) (ReadSessionDataRow, error) {
	row := q.db.QueryRowContext(ctx, readSessionData, arg.SessionID, arg.ExpiresAt)
	var i ReadSessionDataRow
	err := row.Scan(
		&i.Csrf,
		&i.UserID,
		&i.Handle,
		&i.IsActive,
		&i.IsAdmin,
		&i.IsGm,
		&i.IsGuest,
		&i.IsPlayer,
		&i.IsService,
		&i.IsSysop,
		&i.IsUser,
	)
	return i, err
}

const reapSessions = `-- name: ReapSessions :exec
DELETE
FROM sessions
WHERE expires_at <= ?1
`

// ReapSessions deletes expired sessions.
func (q *Queries) ReapSessions(ctx context.Context, nowUtc int64) error {
	_, err := q.db.ExecContext(ctx, reapSessions, nowUtc)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET expires_at = ?1,
    updated_at = ?2
WHERE session_id = ?3
`

type UpdateSessionParams struct {
	ExpiresAt int64
	UpdatedAt int64
	SessionID string
}

// UpdateSession updates a session.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.ExpiresAt, arg.UpdatedAt, arg.SessionID)
	return err
}
