// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timezones.sql

package sqlc

import (
	"context"
)

const getActiveTimezones = `-- name: GetActiveTimezones :many

SELECT distinct timezone
FROM users
ORDER BY 1
`

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// GetActiveTimezones returns the timezones that are used by users.
func (q *Queries) GetActiveTimezones(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var timezone string
		if err := rows.Scan(&timezone); err != nil {
			return nil, err
		}
		items = append(items, timezone)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
