// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (username,
                   email,
                   handle,
                   timezone,
                   created_at,
                   updated_at)
VALUES (?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6)
RETURNING user_id
`

type CreateUserParams struct {
	Username  string
	Email     string
	Handle    string
	Timezone  string
	CreatedAt int64
	UpdatedAt int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreateUser creates a new user and returns its id.
// The email must be lowercase and unique.
// Timezone is the user's timezone. Use UTC if unknown.
// The password is stored as a bcrypt hash.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Handle,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
ORDER BY username
`

// GetAllUsers returns all users.
func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Handle,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
WHERE email = ?1
`

// GetUserByEmail returns the user with the given email address.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
WHERE handle = ?1
`

// GetUserByHandle returns the user with the given handle.
func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
WHERE user_id = ?1
`

// GetUserByID returns the user with the given id.
func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
WHERE username = ?1
`

// GetUserByUsername returns the user with the given username.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT user_id
FROM users
WHERE email = ?1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserIDByHandle = `-- name: GetUserIDByHandle :one
SELECT user_id
FROM users
WHERE handle = ?1
`

func (q *Queries) GetUserIDByHandle(ctx context.Context, handle string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByHandle, handle)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserIDByUsername = `-- name: GetUserIDByUsername :one
SELECT user_id
FROM users
WHERE username = ?1
`

func (q *Queries) GetUserIDByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByUsername, username)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const listUsersVisibleToActor = `-- name: ListUsersVisibleToActor :many
SELECT user_id,
       username,
       email,
       handle,
       timezone,
       created_at,
       updated_at
FROM users
WHERE ?1 = 1
  AND ?2 = 1
  AND ?3 = 1
ORDER BY username
`

type ListUsersVisibleToActorParams struct {
	ActorID  interface{}
	PageSize interface{}
	PageNum  interface{}
}

func (q *Queries) ListUsersVisibleToActor(ctx context.Context, arg ListUsersVisibleToActorParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersVisibleToActor, arg.ActorID, arg.PageSize, arg.PageNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Handle,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email      = ?1,
    username   = ?2,
    handle     = ?3,
    timezone   = ?4,
    updated_at = ?5
WHERE user_id = ?6
`

type UpdateUserParams struct {
	Email     string
	Username  string
	Handle    string
	Timezone  string
	UpdatedAt int64
	UserID    int64
}

// UpdateUser updates the given user.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.Handle,
		arg.Timezone,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email      = ?1,
    updated_at = ?2
WHERE user_id = ?3
`

type UpdateUserEmailParams struct {
	Email     string
	UpdatedAt int64
	UserID    int64
}

// UpdateUserEmail updates the email for the given user.
func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
SET username   = ?1,
    updated_at = ?2
WHERE user_id = ?3
`

type UpdateUserNameParams struct {
	Username  string
	UpdatedAt int64
	UserID    int64
}

// UpdateUserName updates the name for the given user.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserName, arg.Username, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :exec
UPDATE users
SET timezone   = ?1,
    updated_at = ?2
WHERE user_id = ?3
`

type UpdateUserTimezoneParams struct {
	Timezone  string
	UpdatedAt int64
	UserID    int64
}

// UpdateUserTimezone updates the timezone for the given user.
func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTimezone, arg.Timezone, arg.UpdatedAt, arg.UserID)
	return err
}
