// Code generated by "stringer --type Kind"; DO NOT EDIT.

package cst2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Base-0]
	_ = x[TurnReport-1]
	_ = x[PrologueSection-2]
	_ = x[Line-3]
	_ = x[UnitSection-4]
	_ = x[UnitLine-5]
	_ = x[BadUnitSection-6]
	_ = x[EpilogueSection-7]
}

const _Kind_name = "BaseTurnReportPrologueSectionLineUnitSectionUnitLineBadUnitSectionEpilogueSection"

var _Kind_index = [...]uint8{0, 4, 14, 29, 33, 44, 52, 66, 81}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
