// Code generated by pigeon; DO NOT EDIT.

package reports

// NB: including all the imports make the parser generator run a bit more quickly.
import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "ReportFile",
			pos:  position{line: 23, col: 1, offset: 235},
			expr: &actionExpr{
				pos: position{line: 23, col: 15, offset: 249},
				run: (*parser).callonReportFile1,
				expr: &seqExpr{
					pos: position{line: 23, col: 15, offset: 249},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 23, col: 15, offset: 249},
							label: "cs",
							expr: &ruleRefExpr{
								pos:  position{line: 23, col: 18, offset: 252},
								name: "ClanSection",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 30, offset: 264},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 32, offset: 266},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "ClanSection",
			pos:  position{line: 52, col: 1, offset: 1271},
			expr: &actionExpr{
				pos: position{line: 52, col: 16, offset: 1286},
				run: (*parser).callonClanSection1,
				expr: &seqExpr{
					pos: position{line: 52, col: 16, offset: 1286},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 52, col: 16, offset: 1286},
							label: "loc",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 20, offset: 1290},
								name: "ClanLocationLine",
							},
						},
						&labeledExpr{
							pos:   position{line: 52, col: 37, offset: 1307},
							label: "turn",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 42, offset: 1312},
								name: "CurrentTurnLine",
							},
						},
						&labeledExpr{
							pos:   position{line: 52, col: 58, offset: 1328},
							label: "scoutLines",
							expr: &zeroOrMoreExpr{
								pos: position{line: 52, col: 69, offset: 1339},
								expr: &ruleRefExpr{
									pos:  position{line: 52, col: 69, offset: 1339},
									name: "ScoutLine",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ClanLocationLine",
			pos:  position{line: 68, col: 1, offset: 1827},
			expr: &actionExpr{
				pos: position{line: 68, col: 21, offset: 1847},
				run: (*parser).callonClanLocationLine1,
				expr: &seqExpr{
					pos: position{line: 68, col: 21, offset: 1847},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 68, col: 21, offset: 1847},
							val:        "Tribe",
							ignoreCase: false,
							want:       "\"Tribe\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 29, offset: 1855},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 32, offset: 1858},
							label: "u",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 34, offset: 1860},
								name: "ClanUnitId",
							},
						},
						&litMatcher{
							pos:        position{line: 68, col: 45, offset: 1871},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 49, offset: 1875},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 68, col: 52, offset: 1878},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 56, offset: 1882},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 68, col: 59, offset: 1885},
							val:        "Current Hex =",
							ignoreCase: false,
							want:       "\"Current Hex =\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 75, offset: 1901},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 78, offset: 1904},
							label: "ch",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 81, offset: 1907},
								name: "Coords",
							},
						},
						&litMatcher{
							pos:        position{line: 68, col: 88, offset: 1914},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 92, offset: 1918},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 68, col: 95, offset: 1921},
							val:        "(Previous Hex =",
							ignoreCase: false,
							want:       "\"(Previous Hex =\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 113, offset: 1939},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 116, offset: 1942},
							label: "ph",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 119, offset: 1945},
								name: "Coords",
							},
						},
						&litMatcher{
							pos:        position{line: 68, col: 126, offset: 1952},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 130, offset: 1956},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "CurrentTurnLine",
			pos:  position{line: 76, col: 1, offset: 2091},
			expr: &actionExpr{
				pos: position{line: 76, col: 20, offset: 2110},
				run: (*parser).callonCurrentTurnLine1,
				expr: &seqExpr{
					pos: position{line: 76, col: 20, offset: 2110},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 76, col: 20, offset: 2110},
							val:        "Current Turn",
							ignoreCase: false,
							want:       "\"Current Turn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 35, offset: 2125},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 76, col: 38, offset: 2128},
							label: "cym",
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 42, offset: 2132},
								name: "TurnYearMonth",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 56, offset: 2146},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 76, col: 59, offset: 2149},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 76, col: 63, offset: 2153},
							label: "cno",
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 67, offset: 2157},
								name: "TurnNo",
							},
						},
						&litMatcher{
							pos:        position{line: 76, col: 74, offset: 2164},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&litMatcher{
							pos:        position{line: 76, col: 78, offset: 2168},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 82, offset: 2172},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 85, offset: 2175},
							name: "Season",
						},
						&litMatcher{
							pos:        position{line: 76, col: 92, offset: 2182},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 96, offset: 2186},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 99, offset: 2189},
							name: "Weather",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 107, offset: 2197},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 76, col: 110, offset: 2200},
							val:        "Next Turn",
							ignoreCase: false,
							want:       "\"Next Turn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 122, offset: 2212},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 125, offset: 2215},
							name: "TurnYearMonth",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 139, offset: 2229},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 76, col: 142, offset: 2232},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 146, offset: 2236},
							name: "TurnNo",
						},
						&litMatcher{
							pos:        position{line: 76, col: 153, offset: 2243},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&litMatcher{
							pos:        position{line: 76, col: 157, offset: 2247},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 161, offset: 2251},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 164, offset: 2254},
							name: "REPORT_DATE",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 176, offset: 2266},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "Season",
			pos:  position{line: 89, col: 1, offset: 2576},
			expr: &actionExpr{
				pos: position{line: 89, col: 11, offset: 2586},
				run: (*parser).callonSeason1,
				expr: &choiceExpr{
					pos: position{line: 89, col: 13, offset: 2588},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 89, col: 13, offset: 2588},
							val:        "Winter",
							ignoreCase: false,
							want:       "\"Winter\"",
						},
						&litMatcher{
							pos:        position{line: 89, col: 24, offset: 2599},
							val:        "Spring",
							ignoreCase: false,
							want:       "\"Spring\"",
						},
					},
				},
			},
		},
		{
			name: "Weather",
			pos:  position{line: 93, col: 1, offset: 2646},
			expr: &actionExpr{
				pos: position{line: 93, col: 12, offset: 2657},
				run: (*parser).callonWeather1,
				expr: &litMatcher{
					pos:        position{line: 93, col: 12, offset: 2657},
					val:        "FINE",
					ignoreCase: false,
					want:       "\"FINE\"",
				},
			},
		},
		{
			name: "Coords",
			pos:  position{line: 100, col: 1, offset: 2765},
			expr: &choiceExpr{
				pos: position{line: 100, col: 11, offset: 2775},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 100, col: 11, offset: 2775},
						run: (*parser).callonCoords2,
						expr: &seqExpr{
							pos: position{line: 100, col: 11, offset: 2775},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 100, col: 11, offset: 2775},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 18, offset: 2782},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 25, offset: 2789},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 28, offset: 2792},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 34, offset: 2798},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 40, offset: 2804},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 100, col: 46, offset: 2810},
									name: "DIGIT",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 108, col: 5, offset: 3040},
						run: (*parser).callonCoords11,
						expr: &seqExpr{
							pos: position{line: 108, col: 5, offset: 3040},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 108, col: 5, offset: 3040},
									val:        "##",
									ignoreCase: false,
									want:       "\"##\"",
								},
								&ruleRefExpr{
									pos:  position{line: 108, col: 10, offset: 3045},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 108, col: 13, offset: 3048},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 108, col: 19, offset: 3054},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 108, col: 25, offset: 3060},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 108, col: 31, offset: 3066},
									name: "DIGIT",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 116, col: 5, offset: 3281},
						run: (*parser).callonCoords19,
						expr: &litMatcher{
							pos:        position{line: 116, col: 5, offset: 3281},
							val:        "N/A",
							ignoreCase: false,
							want:       "\"N/A\"",
						},
					},
				},
			},
		},
		{
			name: "TurnNo",
			pos:  position{line: 120, col: 1, offset: 3329},
			expr: &actionExpr{
				pos: position{line: 120, col: 11, offset: 3339},
				run: (*parser).callonTurnNo1,
				expr: &seqExpr{
					pos: position{line: 120, col: 11, offset: 3339},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 120, col: 11, offset: 3339},
							val:        "#",
							ignoreCase: false,
							want:       "\"#\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 120, col: 15, offset: 3343},
							expr: &ruleRefExpr{
								pos:  position{line: 120, col: 15, offset: 3343},
								name: "DIGIT",
							},
						},
					},
				},
			},
		},
		{
			name: "TurnYearMonth",
			pos:  position{line: 124, col: 1, offset: 3386},
			expr: &actionExpr{
				pos: position{line: 124, col: 18, offset: 3403},
				run: (*parser).callonTurnYearMonth1,
				expr: &seqExpr{
					pos: position{line: 124, col: 18, offset: 3403},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 124, col: 18, offset: 3403},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 124, col: 24, offset: 3409},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 124, col: 30, offset: 3415},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 124, col: 36, offset: 3421},
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 36, offset: 3421},
								name: "DIGIT",
							},
						},
						&litMatcher{
							pos:        position{line: 124, col: 43, offset: 3428},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&ruleRefExpr{
							pos:  position{line: 124, col: 47, offset: 3432},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 124, col: 53, offset: 3438},
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 53, offset: 3438},
								name: "DIGIT",
							},
						},
					},
				},
			},
		},
		{
			name: "ClanUnitId",
			pos:  position{line: 128, col: 1, offset: 3481},
			expr: &actionExpr{
				pos: position{line: 128, col: 15, offset: 3495},
				run: (*parser).callonClanUnitId1,
				expr: &seqExpr{
					pos: position{line: 128, col: 15, offset: 3495},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 128, col: 15, offset: 3495},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
						&ruleRefExpr{
							pos:  position{line: 128, col: 19, offset: 3499},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 128, col: 25, offset: 3505},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 128, col: 31, offset: 3511},
							name: "DIGIT",
						},
					},
				},
			},
		},
		{
			name: "ScoutLine",
			pos:  position{line: 132, col: 1, offset: 3562},
			expr: &actionExpr{
				pos: position{line: 132, col: 14, offset: 3575},
				run: (*parser).callonScoutLine1,
				expr: &seqExpr{
					pos: position{line: 132, col: 14, offset: 3575},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 132, col: 14, offset: 3575},
							val:        "Scout",
							ignoreCase: false,
							want:       "\"Scout\"",
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 22, offset: 3583},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 25, offset: 3586},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 28, offset: 3589},
								name: "ScoutID",
							},
						},
						&litMatcher{
							pos:        position{line: 132, col: 36, offset: 3597},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&litMatcher{
							pos:        position{line: 132, col: 40, offset: 3601},
							val:        "Scout",
							ignoreCase: false,
							want:       "\"Scout\"",
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 48, offset: 3609},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 51, offset: 3612},
							label: "moves",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 57, offset: 3618},
								name: "ScoutMoves",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 68, offset: 3629},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "ScoutID",
			pos:  position{line: 141, col: 1, offset: 3816},
			expr: &actionExpr{
				pos: position{line: 141, col: 12, offset: 3827},
				run: (*parser).callonScoutID1,
				expr: &charClassMatcher{
					pos:        position{line: 141, col: 12, offset: 3827},
					val:        "[1-8]",
					ranges:     []rune{'1', '8'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "ScoutMoves",
			pos:  position{line: 145, col: 1, offset: 3880},
			expr: &actionExpr{
				pos: position{line: 145, col: 15, offset: 3894},
				run: (*parser).callonScoutMoves1,
				expr: &seqExpr{
					pos: position{line: 145, col: 15, offset: 3894},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 145, col: 15, offset: 3894},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 145, col: 21, offset: 3900},
								name: "ScoutMove",
							},
						},
						&labeledExpr{
							pos:   position{line: 145, col: 31, offset: 3910},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 145, col: 36, offset: 3915},
								expr: &actionExpr{
									pos: position{line: 145, col: 37, offset: 3916},
									run: (*parser).callonScoutMoves7,
									expr: &seqExpr{
										pos: position{line: 145, col: 37, offset: 3916},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 145, col: 37, offset: 3916},
												name: "BACKSLASH",
											},
											&labeledExpr{
												pos:   position{line: 145, col: 47, offset: 3926},
												label: "m",
												expr: &ruleRefExpr{
													pos:  position{line: 145, col: 49, offset: 3928},
													name: "ScoutMove",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ScoutMove",
			pos:  position{line: 155, col: 1, offset: 4144},
			expr: &choiceExpr{
				pos: position{line: 155, col: 14, offset: 4157},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 155, col: 14, offset: 4157},
						run: (*parser).callonScoutMove2,
						expr: &labeledExpr{
							pos:   position{line: 155, col: 14, offset: 4157},
							label: "moved",
							expr: &ruleRefExpr{
								pos:  position{line: 155, col: 20, offset: 4163},
								name: "ScoutMoved",
							},
						},
					},
					&actionExpr{
						pos: position{line: 157, col: 5, offset: 4237},
						run: (*parser).callonScoutMove5,
						expr: &labeledExpr{
							pos:   position{line: 157, col: 5, offset: 4237},
							label: "failed",
							expr: &ruleRefExpr{
								pos:  position{line: 157, col: 12, offset: 4244},
								name: "ScoutFailed",
							},
						},
					},
					&actionExpr{
						pos: position{line: 159, col: 5, offset: 4299},
						run: (*parser).callonScoutMove8,
						expr: &labeledExpr{
							pos:   position{line: 159, col: 5, offset: 4299},
							label: "patrolled",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 15, offset: 4309},
								name: "ScoutPatrolled",
							},
						},
					},
					&actionExpr{
						pos: position{line: 161, col: 5, offset: 4399},
						run: (*parser).callonScoutMove11,
						expr: &oneOrMoreExpr{
							pos: position{line: 161, col: 5, offset: 4399},
							expr: &seqExpr{
								pos: position{line: 161, col: 6, offset: 4400},
								exprs: []any{
									&notExpr{
										pos: position{line: 161, col: 6, offset: 4400},
										expr: &ruleRefExpr{
											pos:  position{line: 161, col: 7, offset: 4401},
											name: "BACKSLASH",
										},
									},
									&notExpr{
										pos: position{line: 161, col: 17, offset: 4411},
										expr: &ruleRefExpr{
											pos:  position{line: 161, col: 18, offset: 4412},
											name: "EOL",
										},
									},
									&anyMatcher{
										line: 161, col: 22, offset: 4416,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ScoutFailed",
			pos:  position{line: 167, col: 1, offset: 4498},
			expr: &choiceExpr{
				pos: position{line: 167, col: 16, offset: 4513},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 167, col: 16, offset: 4513},
						run: (*parser).callonScoutFailed2,
						expr: &seqExpr{
							pos: position{line: 167, col: 16, offset: 4513},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 167, col: 16, offset: 4513},
									val:        ",Can't Move on Lake to ",
									ignoreCase: false,
									want:       "\",Can't Move on Lake to \"",
								},
								&labeledExpr{
									pos:   position{line: 167, col: 42, offset: 4539},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 167, col: 44, offset: 4541},
										name: "Direction",
									},
								},
								&litMatcher{
									pos:        position{line: 167, col: 54, offset: 4551},
									val:        " of HEX",
									ignoreCase: false,
									want:       "\" of HEX\"",
								},
								&labeledExpr{
									pos:   position{line: 167, col: 64, offset: 4561},
									label: "patrolled",
									expr: &zeroOrOneExpr{
										pos: position{line: 167, col: 74, offset: 4571},
										expr: &ruleRefExpr{
											pos:  position{line: 167, col: 74, offset: 4571},
											name: "ScoutPatrolled",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 167, col: 90, offset: 4587},
									expr: &seqExpr{
										pos: position{line: 167, col: 91, offset: 4588},
										exprs: []any{
											&notExpr{
												pos: position{line: 167, col: 91, offset: 4588},
												expr: &ruleRefExpr{
													pos:  position{line: 167, col: 92, offset: 4589},
													name: "BACKSLASH",
												},
											},
											&notExpr{
												pos: position{line: 167, col: 102, offset: 4599},
												expr: &ruleRefExpr{
													pos:  position{line: 167, col: 103, offset: 4600},
													name: "EOL",
												},
											},
											&anyMatcher{
												line: 167, col: 107, offset: 4604,
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 179, col: 5, offset: 4897},
						run: (*parser).callonScoutFailed18,
						expr: &seqExpr{
							pos: position{line: 179, col: 5, offset: 4897},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 179, col: 5, offset: 4897},
									val:        ",Can't Move on Ocean to ",
									ignoreCase: false,
									want:       "\",Can't Move on Ocean to \"",
								},
								&labeledExpr{
									pos:   position{line: 179, col: 32, offset: 4924},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 179, col: 34, offset: 4926},
										name: "Direction",
									},
								},
								&litMatcher{
									pos:        position{line: 179, col: 44, offset: 4936},
									val:        " of HEX",
									ignoreCase: false,
									want:       "\" of HEX\"",
								},
								&labeledExpr{
									pos:   position{line: 179, col: 54, offset: 4946},
									label: "patrolled",
									expr: &zeroOrOneExpr{
										pos: position{line: 179, col: 64, offset: 4956},
										expr: &ruleRefExpr{
											pos:  position{line: 179, col: 64, offset: 4956},
											name: "ScoutPatrolled",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 179, col: 80, offset: 4972},
									expr: &seqExpr{
										pos: position{line: 179, col: 81, offset: 4973},
										exprs: []any{
											&notExpr{
												pos: position{line: 179, col: 81, offset: 4973},
												expr: &ruleRefExpr{
													pos:  position{line: 179, col: 82, offset: 4974},
													name: "BACKSLASH",
												},
											},
											&notExpr{
												pos: position{line: 179, col: 92, offset: 4984},
												expr: &ruleRefExpr{
													pos:  position{line: 179, col: 93, offset: 4985},
													name: "EOL",
												},
											},
											&anyMatcher{
												line: 179, col: 97, offset: 4989,
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 191, col: 5, offset: 5283},
						run: (*parser).callonScoutFailed34,
						expr: &seqExpr{
							pos: position{line: 191, col: 5, offset: 5283},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 191, col: 5, offset: 5283},
									val:        ",No Ford on River to ",
									ignoreCase: false,
									want:       "\",No Ford on River to \"",
								},
								&labeledExpr{
									pos:   position{line: 191, col: 29, offset: 5307},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 191, col: 31, offset: 5309},
										name: "Direction",
									},
								},
								&litMatcher{
									pos:        position{line: 191, col: 41, offset: 5319},
									val:        " of HEX",
									ignoreCase: false,
									want:       "\" of HEX\"",
								},
								&labeledExpr{
									pos:   position{line: 191, col: 51, offset: 5329},
									label: "patrolled",
									expr: &zeroOrOneExpr{
										pos: position{line: 191, col: 61, offset: 5339},
										expr: &ruleRefExpr{
											pos:  position{line: 191, col: 61, offset: 5339},
											name: "ScoutPatrolled",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 191, col: 77, offset: 5355},
									expr: &seqExpr{
										pos: position{line: 191, col: 78, offset: 5356},
										exprs: []any{
											&notExpr{
												pos: position{line: 191, col: 78, offset: 5356},
												expr: &ruleRefExpr{
													pos:  position{line: 191, col: 79, offset: 5357},
													name: "BACKSLASH",
												},
											},
											&notExpr{
												pos: position{line: 191, col: 89, offset: 5367},
												expr: &ruleRefExpr{
													pos:  position{line: 191, col: 90, offset: 5368},
													name: "EOL",
												},
											},
											&anyMatcher{
												line: 191, col: 94, offset: 5372,
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 203, col: 5, offset: 5666},
						run: (*parser).callonScoutFailed50,
						expr: &seqExpr{
							pos: position{line: 203, col: 5, offset: 5666},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 203, col: 5, offset: 5666},
									val:        ",Not enough M.P's to move to ",
									ignoreCase: false,
									want:       "\",Not enough M.P's to move to \"",
								},
								&labeledExpr{
									pos:   position{line: 203, col: 37, offset: 5698},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 203, col: 39, offset: 5700},
										name: "Direction",
									},
								},
								&litMatcher{
									pos:        position{line: 203, col: 49, offset: 5710},
									val:        " into ",
									ignoreCase: false,
									want:       "\" into \"",
								},
								&labeledExpr{
									pos:   position{line: 203, col: 58, offset: 5719},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 203, col: 60, offset: 5721},
										name: "TerrainLong",
									},
								},
								&labeledExpr{
									pos:   position{line: 203, col: 72, offset: 5733},
									label: "patrolled",
									expr: &zeroOrOneExpr{
										pos: position{line: 203, col: 82, offset: 5743},
										expr: &ruleRefExpr{
											pos:  position{line: 203, col: 82, offset: 5743},
											name: "ScoutPatrolled",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 203, col: 98, offset: 5759},
									expr: &seqExpr{
										pos: position{line: 203, col: 99, offset: 5760},
										exprs: []any{
											&notExpr{
												pos: position{line: 203, col: 99, offset: 5760},
												expr: &ruleRefExpr{
													pos:  position{line: 203, col: 100, offset: 5761},
													name: "BACKSLASH",
												},
											},
											&notExpr{
												pos: position{line: 203, col: 110, offset: 5771},
												expr: &ruleRefExpr{
													pos:  position{line: 203, col: 111, offset: 5772},
													name: "EOL",
												},
											},
											&anyMatcher{
												line: 203, col: 115, offset: 5776,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ScoutMoved",
			pos:  position{line: 218, col: 1, offset: 6100},
			expr: &actionExpr{
				pos: position{line: 218, col: 15, offset: 6114},
				run: (*parser).callonScoutMoved1,
				expr: &seqExpr{
					pos: position{line: 218, col: 15, offset: 6114},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 218, col: 15, offset: 6114},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 218, col: 17, offset: 6116},
								name: "Direction",
							},
						},
						&litMatcher{
							pos:        position{line: 218, col: 27, offset: 6126},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 218, col: 31, offset: 6130},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 218, col: 33, offset: 6132},
								name: "Terrain",
							},
						},
						&labeledExpr{
							pos:   position{line: 218, col: 41, offset: 6140},
							label: "rest",
							expr: &oneOrMoreExpr{
								pos: position{line: 218, col: 46, offset: 6145},
								expr: &seqExpr{
									pos: position{line: 218, col: 47, offset: 6146},
									exprs: []any{
										&notExpr{
											pos: position{line: 218, col: 47, offset: 6146},
											expr: &ruleRefExpr{
												pos:  position{line: 218, col: 48, offset: 6147},
												name: "BACKSLASH",
											},
										},
										&notExpr{
											pos: position{line: 218, col: 58, offset: 6157},
											expr: &ruleRefExpr{
												pos:  position{line: 218, col: 59, offset: 6158},
												name: "EOL",
											},
										},
										&anyMatcher{
											line: 218, col: 63, offset: 6162,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ScoutPatrolled",
			pos:  position{line: 226, col: 1, offset: 6297},
			expr: &actionExpr{
				pos: position{line: 226, col: 19, offset: 6315},
				run: (*parser).callonScoutPatrolled1,
				expr: &litMatcher{
					pos:        position{line: 226, col: 19, offset: 6315},
					val:        ", Nothing of interest found",
					ignoreCase: false,
					want:       "\", Nothing of interest found\"",
				},
			},
		},
		{
			name: "Direction",
			pos:  position{line: 233, col: 1, offset: 6453},
			expr: &actionExpr{
				pos: position{line: 233, col: 14, offset: 6466},
				run: (*parser).callonDirection1,
				expr: &seqExpr{
					pos: position{line: 233, col: 14, offset: 6466},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 233, col: 15, offset: 6467},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 233, col: 15, offset: 6467},
									val:        "NE",
									ignoreCase: false,
									want:       "\"NE\"",
								},
								&litMatcher{
									pos:        position{line: 233, col: 22, offset: 6474},
									val:        "NW",
									ignoreCase: false,
									want:       "\"NW\"",
								},
								&litMatcher{
									pos:        position{line: 233, col: 29, offset: 6481},
									val:        "SE",
									ignoreCase: false,
									want:       "\"SE\"",
								},
								&litMatcher{
									pos:        position{line: 233, col: 36, offset: 6488},
									val:        "SW",
									ignoreCase: false,
									want:       "\"SW\"",
								},
								&litMatcher{
									pos:        position{line: 233, col: 43, offset: 6495},
									val:        "N",
									ignoreCase: false,
									want:       "\"N\"",
								},
								&litMatcher{
									pos:        position{line: 233, col: 49, offset: 6501},
									val:        "S",
									ignoreCase: false,
									want:       "\"S\"",
								},
							},
						},
						&andExpr{
							pos: position{line: 233, col: 54, offset: 6506},
							expr: &choiceExpr{
								pos: position{line: 233, col: 56, offset: 6508},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 233, col: 56, offset: 6508},
										name: "SP",
									},
									&ruleRefExpr{
										pos:  position{line: 233, col: 61, offset: 6513},
										name: "COMMA",
									},
									&ruleRefExpr{
										pos:  position{line: 233, col: 69, offset: 6521},
										name: "BACKSLASH",
									},
									&litMatcher{
										pos:        position{line: 233, col: 81, offset: 6533},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Terrain",
			pos:  position{line: 237, col: 1, offset: 6574},
			expr: &actionExpr{
				pos: position{line: 237, col: 12, offset: 6585},
				run: (*parser).callonTerrain1,
				expr: &seqExpr{
					pos: position{line: 237, col: 12, offset: 6585},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 237, col: 13, offset: 6586},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 237, col: 13, offset: 6586},
									val:        "BF",
									ignoreCase: false,
									want:       "\"BF\"",
								},
								&litMatcher{
									pos:        position{line: 237, col: 20, offset: 6593},
									val:        "GH",
									ignoreCase: false,
									want:       "\"GH\"",
								},
								&litMatcher{
									pos:        position{line: 237, col: 27, offset: 6600},
									val:        "JH",
									ignoreCase: false,
									want:       "\"JH\"",
								},
								&litMatcher{
									pos:        position{line: 237, col: 34, offset: 6607},
									val:        "PR",
									ignoreCase: false,
									want:       "\"PR\"",
								},
							},
						},
						&andExpr{
							pos: position{line: 237, col: 40, offset: 6613},
							expr: &choiceExpr{
								pos: position{line: 237, col: 42, offset: 6615},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 237, col: 42, offset: 6615},
										name: "SP",
									},
									&ruleRefExpr{
										pos:  position{line: 237, col: 47, offset: 6620},
										name: "COMMA",
									},
									&ruleRefExpr{
										pos:  position{line: 237, col: 55, offset: 6628},
										name: "BACKSLASH",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TerrainLong",
			pos:  position{line: 241, col: 1, offset: 6676},
			expr: &actionExpr{
				pos: position{line: 241, col: 16, offset: 6691},
				run: (*parser).callonTerrainLong1,
				expr: &seqExpr{
					pos: position{line: 241, col: 16, offset: 6691},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 241, col: 17, offset: 6692},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 241, col: 17, offset: 6692},
									val:        "BRUSH FLAT",
									ignoreCase: false,
									want:       "\"BRUSH FLAT\"",
								},
								&litMatcher{
									pos:        position{line: 241, col: 32, offset: 6707},
									val:        "GRASSY HILLS",
									ignoreCase: false,
									want:       "\"GRASSY HILLS\"",
								},
								&litMatcher{
									pos:        position{line: 241, col: 49, offset: 6724},
									val:        "PRAIRIE",
									ignoreCase: false,
									want:       "\"PRAIRIE\"",
								},
							},
						},
						&andExpr{
							pos: position{line: 241, col: 60, offset: 6735},
							expr: &choiceExpr{
								pos: position{line: 241, col: 62, offset: 6737},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 241, col: 62, offset: 6737},
										name: "SP",
									},
									&ruleRefExpr{
										pos:  position{line: 241, col: 67, offset: 6742},
										name: "COMMA",
									},
									&ruleRefExpr{
										pos:  position{line: 241, col: 75, offset: 6750},
										name: "BACKSLASH",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BACKSLASH",
			pos:  position{line: 245, col: 1, offset: 6798},
			expr: &litMatcher{
				pos:        position{line: 245, col: 19, offset: 6816},
				val:        "\\",
				ignoreCase: false,
				want:       "\"\\\\\"",
			},
		},
		{
			name: "COMMA",
			pos:  position{line: 246, col: 1, offset: 6821},
			expr: &litMatcher{
				pos:        position{line: 246, col: 19, offset: 6839},
				val:        ",",
				ignoreCase: false,
				want:       "\",\"",
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 247, col: 1, offset: 6843},
			expr: &charClassMatcher{
				pos:        position{line: 247, col: 19, offset: 6861},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 248, col: 1, offset: 6867},
			expr: &seqExpr{
				pos: position{line: 248, col: 19, offset: 6885},
				exprs: []any{
					&zeroOrMoreExpr{
						pos: position{line: 248, col: 19, offset: 6885},
						expr: &anyMatcher{
							line: 248, col: 19, offset: 6885,
						},
					},
					&notExpr{
						pos: position{line: 248, col: 22, offset: 6888},
						expr: &anyMatcher{
							line: 248, col: 23, offset: 6889,
						},
					},
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 249, col: 1, offset: 6891},
			expr: &litMatcher{
				pos:        position{line: 249, col: 19, offset: 6909},
				val:        "\n",
				ignoreCase: false,
				want:       "\"\\n\"",
			},
		},
		{
			name: "LETTER",
			pos:  position{line: 250, col: 1, offset: 6914},
			expr: &charClassMatcher{
				pos:        position{line: 250, col: 19, offset: 6932},
				val:        "[A-Z]",
				ranges:     []rune{'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "REPORT_DATE",
			pos:  position{line: 251, col: 1, offset: 6938},
			expr: &seqExpr{
				pos: position{line: 251, col: 19, offset: 6956},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 251, col: 19, offset: 6956},
						name: "DIGIT",
					},
					&zeroOrOneExpr{
						pos: position{line: 251, col: 25, offset: 6962},
						expr: &ruleRefExpr{
							pos:  position{line: 251, col: 25, offset: 6962},
							name: "DIGIT",
						},
					},
					&litMatcher{
						pos:        position{line: 251, col: 32, offset: 6969},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 36, offset: 6973},
						name: "DIGIT",
					},
					&zeroOrOneExpr{
						pos: position{line: 251, col: 42, offset: 6979},
						expr: &ruleRefExpr{
							pos:  position{line: 251, col: 42, offset: 6979},
							name: "DIGIT",
						},
					},
					&litMatcher{
						pos:        position{line: 251, col: 49, offset: 6986},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 53, offset: 6990},
						name: "DIGIT",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 59, offset: 6996},
						name: "DIGIT",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 65, offset: 7002},
						name: "DIGIT",
					},
					&ruleRefExpr{
						pos:  position{line: 251, col: 71, offset: 7008},
						name: "DIGIT",
					},
				},
			},
		},
		{
			name: "SP",
			pos:  position{line: 252, col: 1, offset: 7014},
			expr: &litMatcher{
				pos:        position{line: 252, col: 19, offset: 7032},
				val:        " ",
				ignoreCase: false,
				want:       "\" \"",
			},
		},
		{
			name: "_",
			pos:  position{line: 253, col: 1, offset: 7036},
			expr: &zeroOrMoreExpr{
				pos: position{line: 253, col: 19, offset: 7054},
				expr: &charClassMatcher{
					pos:        position{line: 253, col: 19, offset: 7054},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onReportFile1(cs any) (any, error) {
	clanSection := cs.(*gSection)
	return &ReportFile_t{
		Clan: &ClanSection_t{
			Id: UnitId_t(clanSection.location.unitId),
			CurrentHex: Coords_t{
				Grid: clanSection.location.current.grid,
				Col:  clanSection.location.current.col,
				Row:  clanSection.location.current.row,
			},
			PreviousHex: Coords_t{
				Grid: clanSection.location.previous.grid,
				Col:  clanSection.location.previous.col,
				Row:  clanSection.location.previous.row,
			},
			CurrentTurn: &TurnInfo_t{
				Year:  clanSection.turn.current.year,
				Month: clanSection.turn.current.month,
				No:    clanSection.turn.current.no,
			},
		},
		Turn: &TurnInfo_t{
			Year:  clanSection.turn.current.year,
			Month: clanSection.turn.current.month,
			No:    clanSection.turn.current.no,
		},
	}, nil
}

func (p *parser) callonReportFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReportFile1(stack["cs"])
}

func (c *current) onClanSection1(loc, turn, scoutLines any) (any, error) {
	section := &gSection{
		location: loc.(*gLocation),
		turn:     turn.(*gTurnLine),
	}
	for _, scoutLine := range toAnySlice(scoutLines) {
		section.scoutLines = append(section.scoutLines, scoutLine.(*gScoutLine))
	}
	//if buf, err := json.MarshalIndent(section.scoutLines, "", "  "); err != nil {
	//    log.Printf("scoutLines %v\n", err)
	//} else {
	//    log.Printf("scoutLines %s\n", string(buf))
	//}
	return section, nil
}

func (p *parser) callonClanSection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClanSection1(stack["loc"], stack["turn"], stack["scoutLines"])
}

func (c *current) onClanLocationLine1(u, ch, ph any) (any, error) {
	return &gLocation{
		unitId:   u.(gUnitId),
		current:  ch.(gCoords),
		previous: ph.(gCoords),
	}, nil
}

func (p *parser) callonClanLocationLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClanLocationLine1(stack["u"], stack["ch"], stack["ph"])
}

func (c *current) onCurrentTurnLine1(cym, cno any) (any, error) {
	var current gTurn
	yyyymm := cym.(string)
	yyyy, mm, _ := strings.Cut(yyyymm, "-")
	current.year, _ = strconv.Atoi(yyyy)
	current.month, _ = strconv.Atoi(mm)
	hno := cno.(string)
	current.no, _ = strconv.Atoi(hno[1:])
	return &gTurnLine{
		current: &current,
	}, nil
}

func (p *parser) callonCurrentTurnLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCurrentTurnLine1(stack["cym"], stack["cno"])
}

func (c *current) onSeason1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSeason1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSeason1()
}

func (c *current) onWeather1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonWeather1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWeather1()
}

func (c *current) onCoords2() (any, error) {
	// AB 0201
	// 0123456
	return gCoords{
		grid: string(c.text[0:2]),
		col:  int(c.text[3]-'0')*10 + int(c.text[4]-'0'),
		row:  int(c.text[5]-'0')*10 + int(c.text[6]-'0'),
	}, nil
}

func (p *parser) callonCoords2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords2()
}

func (c *current) onCoords11() (any, error) {
	// ## 0201
	// 0123456
	return gCoords{
		grid: "##",
		col:  int(c.text[3]-'0')*10 + int(c.text[4]-'0'),
		row:  int(c.text[5]-'0')*10 + int(c.text[6]-'0'),
	}, nil
}

func (p *parser) callonCoords11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords11()
}

func (c *current) onCoords19() (any, error) {
	return gCoords{grid: "N/A"}, nil
}

func (p *parser) callonCoords19() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoords19()
}

func (c *current) onTurnNo1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTurnNo1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTurnNo1()
}

func (c *current) onTurnYearMonth1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTurnYearMonth1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTurnYearMonth1()
}

func (c *current) onClanUnitId1() (any, error) {
	return gUnitId(string(c.text)), nil
}

func (p *parser) callonClanUnitId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClanUnitId1()
}

func (c *current) onScoutLine1(id, moves any) (any, error) {
	// build and return a *ScoutLine node* here
	// e.g. with ID and Moves
	return &gScoutLine{
		Id:    id.(gScoutId),
		Moves: moves.([]*gScoutMove),
	}, nil
}

func (p *parser) callonScoutLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutLine1(stack["id"], stack["moves"])
}

func (c *current) onScoutID1() (any, error) {
	return gScoutId(c.text[0] - '0'), nil
}

func (p *parser) callonScoutID1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutID1()
}

func (c *current) onScoutMoves7(m any) (any, error) {
	return m, nil
}

func (p *parser) callonScoutMoves7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMoves7(stack["m"])
}

func (c *current) onScoutMoves1(first, rest any) (any, error) {
	moves := []*gScoutMove{
		first.(*gScoutMove),
	}
	for _, mv := range toAnySlice(rest) {
		moves = append(moves, mv.(*gScoutMove))
	}
	return moves, nil
}

func (p *parser) callonScoutMoves1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMoves1(stack["first"], stack["rest"])
}

func (c *current) onScoutMove2(moved any) (any, error) {
	return &gScoutMove{Moved: moved.(*gScoutMoved)}, nil
}

func (p *parser) callonScoutMove2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMove2(stack["moved"])
}

func (c *current) onScoutMove5(failed any) (any, error) {
	return failed.(*gScoutMove), nil
}

func (p *parser) callonScoutMove5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMove5(stack["failed"])
}

func (c *current) onScoutMove8(patrolled any) (any, error) {
	return &gScoutMove{Patrolled: patrolled.(*gScoutPatrolled)}, nil
}

func (p *parser) callonScoutMove8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMove8(stack["patrolled"])
}

func (c *current) onScoutMove11() (any, error) {
	return &gScoutMove{
		Move: "***" + string(c.text),
	}, nil
}

func (p *parser) callonScoutMove11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMove11()
}

func (c *current) onScoutFailed2(d, patrolled any) (any, error) {
	move := &gScoutMove{
		Failed: &gScoutFailed{
			Move:          string(c.text),
			Direction:     d.(string),
			BlockedByLake: true,
		},
	}
	if patrolled != nil {
		move.Patrolled = patrolled.(*gScoutPatrolled)
	}
	return move, nil
}

func (p *parser) callonScoutFailed2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutFailed2(stack["d"], stack["patrolled"])
}

func (c *current) onScoutFailed18(d, patrolled any) (any, error) {
	move := &gScoutMove{
		Failed: &gScoutFailed{
			Move:           string(c.text),
			Direction:      d.(string),
			BlockedByOcean: true,
		},
	}
	if patrolled != nil {
		move.Patrolled = patrolled.(*gScoutPatrolled)
	}
	return move, nil
}

func (p *parser) callonScoutFailed18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutFailed18(stack["d"], stack["patrolled"])
}

func (c *current) onScoutFailed34(d, patrolled any) (any, error) {
	move := &gScoutMove{
		Failed: &gScoutFailed{
			Move:           string(c.text),
			Direction:      d.(string),
			BlockedByRiver: true,
		},
	}
	if patrolled != nil {
		move.Patrolled = patrolled.(*gScoutPatrolled)
	}
	return move, nil
}

func (p *parser) callonScoutFailed34() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutFailed34(stack["d"], stack["patrolled"])
}

func (c *current) onScoutFailed50(d, t, patrolled any) (any, error) {
	move := &gScoutMove{
		Failed: &gScoutFailed{
			Move:         string(c.text),
			Direction:    d.(string),
			Terrain:      t.(string),
			NotEnoughMPs: true,
		},
	}
	if patrolled != nil {
		move.Patrolled = patrolled.(*gScoutPatrolled)
	}
	return move, nil
}

func (p *parser) callonScoutFailed50() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutFailed50(stack["d"], stack["t"], stack["patrolled"])
}

func (c *current) onScoutMoved1(d, t, rest any) (any, error) {
	return &gScoutMoved{
		Move:      string(c.text),
		Direction: d.(string),
		Terrain:   t.(string),
	}, nil
}

func (p *parser) callonScoutMoved1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutMoved1(stack["d"], stack["t"], stack["rest"])
}

func (c *current) onScoutPatrolled1() (any, error) {
	return &gScoutPatrolled{
		Move:              string(c.text),
		NothingOfInterest: true,
	}, nil
}

func (p *parser) callonScoutPatrolled1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScoutPatrolled1()
}

func (c *current) onDirection1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonDirection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDirection1()
}

func (c *current) onTerrain1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTerrain1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerrain1()
}

func (c *current) onTerrainLong1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTerrainLong1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerrainLong1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
